// countriesData.ts
interface CountryData {
  country_title: string;
  description: string;
  steps: string[];
  requirements: string[];
  questions?: string;
  answer?: string[];
  collapseItems?: any[];
}

const countriesData: { [key: string]: CountryData } = {
  Russia: {
    country_title:
      "Russia is a fine place for students who would love to pursue MBBS. It’s well-being and quality of life attracts the students. The course duration in Russia is 5.8 years. MBBS in Russia is considered as the best option for the students who want to study abroad. The reason it is considered as the best option is the advantage of getting high-quality education at an affordable cost. Russia med­ ical universities are recognized by MCI, WHO, UNESCO, etc. Students are keen to take admission in Russia, because of the Russian service and the students who get mbbs admission in Russia are praiseworthy. Doing MBBS in Russia is a great opportunity for the students. The Russian universities occupy the top 30 in the ranking.",
    questions: "Why Study MBBS in ",
    answer: [
      "The quality of education is very affordable and advanced.",
      "Russian degree is globally recognized; therefore, students can practice wherever they wish.",
      "The course is recognized by relevant authorities.",
      "Students get good and furnished accommodation inside the campus.",
      "The students who are from India feel at home because of the Indian mess in the universities.",
      "The subsidy is 70% for the MBBS courses in Russian Universities. The average MBBS fee is between 2.5 Lakhs to 5 Lakhs per year.",
      "MCI Screening Test is provided by most of the Russian universities. Graduates show excellent results in the FMGE exam as a result and land in the best hospitals and industries worldwide.",
      "Technically Equipped Learning - Russia is known for the advanced medical facilities.",
      "Many Specialization Courses - Russian universities provide an ample number of courses for students to choose and specialize.",
      "MBBS in Russia provides goal-oriented education.",
      "Faculties are highly qualified.",
      "Russia uses the latest teaching methods and technologies.",
      "Russia has a proper Indian Hostel and Indian Food (Veg & Non-Veg) which is easily accessible.",
      "The warden for boys and girls is separate and has complete security.",
      "Campus is ragging-free.",
      "Traveling in Russia is comparatively low-cost.",
      "Over 1000 students study at top medical colleges in Russia.",
    ],
    description:
      "Russia is a fine place for students who would love to pursue MBBS. It’s well-being and quality of life attracts the students. The course duration in Russia is 5.8 years. MBBS in Russia is considered as the best option for the students who want to study abroad. The reason it is considered as the best option is the advantage of getting high-quality education at an affordable cost. Russia med­ ical universities are recognized by MCI, WHO, UNESCO, etc. Students are keen to take admission in Russia, because of the Russian service and the students who get mbbs admission in Russia are praiseworthy. Doing MBBS in Russia is a great opportunity for the students. The Russian universities occupy the top 30 in the ranking.",
    steps: [
      "Applying for MBBS abroad can seem daunting, but with MOC - Medico Overseas Consultancy, the process is straightforward and hassle-free.",
      "Here’s a step-by-step guide to help you through the application process:",
      "Step 1: Research - Identify your preferred country and university with the help of MOC’s expert consultants.",
      "Step 2: Eligibility Check - Ensure you meet the eligibility criteria, including academic qualifications and language proficiency.",
      "Step 3: Document Preparation - Prepare necessary documents such as transcripts, passport, and medical certificates.",
      "Step 4: Application Submission - Submit your application through MOC to your chosen university.",
      "Step 5: Entrance Exams - Some universities may require entrance exams or interviews. Prepare accordingly.",
      "Step 6: Admission Confirmation - Receive your admission offer and confirm your seat.",
      "Step 7: Visa Application - Apply for a student visa with guidance from MOC.",
      "Step 8: Travel Arrangements - Make travel arrangements and plan your journey.",
      "Step 9: Arrival and Accommodation - Upon arrival, MOC assists with accommodation and settling in.",
      "Start your journey with MOC today and achieve your dream of studying MBBS abroad.",
      "Choose MOC for a reliable and successful MBBS abroad experience. Contact us today to get started on your path to a fulfilling medical career.",
    ],
    requirements: [
      "Candidate must submit the application form.",
      "Candidates must have a NEET-UG examination scorecard along with the admit card.",
      "The academic mark sheet and passing certificate (original and copy).",
      "The candidate must carry a transfer certificate / leaving certificate from the previous institution.",
      "Foreign students must have a valid passport.",
      "Birth certificates must be submitted during admission required for proof of date of birth.",
      "Provisional allotment letter generated online.",
      "Candidates must submit caste certificate and validity certificate. (SC/ST/OBC category candidates)",
      "Submit your ID proof during admission time (Aadhaar card/ PAN card/ driving license/ passport).",
      "Conduct and character certificate.",
      "Candidates should submit the medical certificate.",
      "Carry passport size photographs required for MBBS admission.",
      "Proof of nationality of India / Passport/ domicile /nationality certificate.",
      "Passport size photographs.",
      "Demand draft.",
      "Gap certificate (Affidavit) (if applicable).",
      "Migration certificate (if applicable).",
    ],
    collapseItems: [
      {
        title: "Our Services",
        servicesOffered: [
          "Counselling.",
          "Pre-Departure Briefing in Our Delhi Head Office.",
          "University Selection.",
          "Airport Drop To IGI Airport (New Delhi).",
          "Documentation.",
          "Airport Pick-Up From the Selected Country Airport.",
          "Provisional Admission.",
          "Bank Loan Assistance.",
          "Assistance & Legalization.",
          "Free 10 Mins Call With Parents From The Destination Airport After Customs Clearance.",
          "Travel Arrangements From the Destination Airport To The University Hostel.",
          "Hostel Room Allotment.",
          "Eligibility Certificate Application.",
          "Free Meals For Initial Few Days.",
          "University Admission.",
          "Visa Application.",
          "City Tour, University Campus Visit.",
        ],
      },
      {
        title: "Admission Application Processing Fee",
        servicesOffered: [
          "Registration Fees Rs. 25000 At the Time of Registration.",
          "Documentation Fee (Ministry Decree, EQE Approval) Rs. 65000 Within 5 days After Receiving Admission Letter.",
          "Invitation, Visa, Insurance & Flight Ticket Rs. 60000 Within 5 days After Receiving Admission Letter.",
        ],
      },
    ],
  },
  Kyrgyzstan: {
    country_title: "Why Kyrgyzstan?",
    description:
      "Kyrgyzstan can be an attractive destination for studies due to its affordable tuition fees, low cost of living, and a growing number of programs taught in English. The country’s universities offer a range of courses in diverse fields, and its beautiful natural landscapes and rich cultural heritage provide a unique backdrop for international students. Additionally, the friendly and welcoming local population makes it easier for students to adapt to a new environment. However, it’s essential to thoroughly research specific universities and programs to ensure they meet your academic and career goals.",

    questions: "Why Study MBBS in ",
    answer: [
      "Affordable Tuition: Kyrgyzstan offers cost-effective medical education compared to many other countries, making it accessible for international students.",
      "Recognized Degrees: Medical degrees from Kyrgyzstan are recognized by major medical councils and organizations worldwide.",
      "Quality Education: Many medical colleges in Kyrgyzstan maintain high educational standards and use English as the medium of instruction.",
      "Skilled Faculty: Kyrgyzstan has experienced and qualified faculty members in medical institutions who provide quality education.",
      "Cultural Diversity: Students can experience a rich cultural diversity and gain exposure to a variety of medical cases.",
      "Low Living Costs: The cost of living in Kyrgyzstan is relatively low, which is beneficial for international students on a budget.",
      "Language Advantage: English is widely spoken and understood, simplifying communication for international students.",
      "Clinical Experience: Students can gain valuable clinical experience in a wide range of medical facilities.",
      "Safety: Kyrgyzstan offers a relatively safe environment for international students.",
      "Admission Opportunities: Many Kyrgyzstan medical colleges offer admission options for international students with straightforward admission processes.",
    ],
    steps: [
      "After completing the visa processing time, get a valid passport and fly for your dreams.",
      "Submission of educational certificates and other essential documents required for MBBS admission.",
      "Admission will be based on merit and performance during the interview.",
      "Candidates will get an offer letter from the university within a couple of days.",
      "Pay 1st-year tuition fee of the MBBS course.",
      "Apply for the visa procedure.",
      "After completing the visa processing time, get a valid passport and fly for your dreams.",
    ],
    requirements: [
      "Candidate must submit the application form.",
      "Candidates must have a NEET-UG examination scorecard along with the admit card.",
      "The academic mark sheet and passing certificate (original and copy).",
      "The candidate must carry a transfer certificate / leaving certificate from the previous institution.",
      "Foreign students must have a valid passport.",
      "Birth certificates must be submitted during admission required for proof of date of birth.",
      "Provisional allotment letter generated online.",
      "Candidates must submit caste certificate and validity certificate. (SC/ST/OBC category candidates)",
      "Submit your ID proof during admission time (Aadhaar card/ PAN card/ driving license/ passport).",
      "Conduct and character certificate.",
      "Candidates should submit the medical certificate.",
      "Carry passport size photographs required for MBBS admission.",
      "Proof of nationality of India / Passport/ domicile /nationality certificate.",
      "Passport size photographs.",
      "Demand draft.",
      "Gap certificate (Affidavit) (if applicable).",
      "Migration certificate (if applicable).",
    ],
    collapseItems: [
      {
        title: "Our Services",
        servicesOffered: [
          "Counselling.",
          "Pre-Departure Briefing in Our Delhi Head Office.",
          "University Selection.",
          "Airport Drop To IGI Airport (New Delhi).",
          "Documentation.",
          "Airport Pick-Up From the Selected Country Airport.",
          "Provisional Admission.",
          "Bank Loan Assistance.",
          "Assistance & Legalization.",
          "Free 10 Mins Call With Parents From The Destination Airport After Customs Clearance.",
          "Travel Arrangements From the Destination Airport To The University Hostel.",
          "Hostel Room Allotment.",
          "Eligibility Certificate Application.",
          "Free Meals For Initial Few Days.",
          "University Admission.",
          "Visa Application.",
          "City Tour, University Campus Visit.",
        ],
      },
      {
        title: "Admission Application Processing Fee",
        servicesOffered: [
          "Registration Fees Rs. 25000 At the Time of Registration.",
          "Documentation Fee (Ministry Decree, EQE Approval) Rs. 65000 Within 5 days After Receiving Admission Letter.",
          "Invitation, Visa, Insurance & Flight Ticket Rs. 60000 Within 5 days After Receiving Admission Letter.",
        ],
      },
    ],
  },
  kazakhstan: {
    country_title: "kazakhstan",
    description:
      "Kazakhstan offers international students a unique and enriching study experience due to its diverse cultural and geographical landscape. It boasts a mix of modern cities and traditional nomadic heritage, making it an intriguing destination for those seeking cultural immersion. Additionally, the country’s educational institutions have been investing in improving their academic programs and infrastructure, providing quality education at a relatively affordable cost compared to many Western countries. With a growing emphasis on internationalization, Kazakhstan is becoming an increasingly attractive option for students seeking a well-rounded and affordable educational experience.",
    questions: "Why Study MBBS in ",
    answer: [
      "Affordable Tuition: Many medical universities in Kazakhstan offer cost-effective tuition fees, making it an economical option for aspiring doctors, especially when compared to Western institutions.",
      "Quality Education: Kazakhstan’s medical universities are recognized by international bodies like the World Health Organization (WHO) and the Medical Council of India (MCI). They follow modern curricula and provide quality education in English, ensuring that graduates are well-prepared for global medical practice.",
      "International Recognition: Graduates of Kazakhstan’s medical universities are eligible to practice medicine in various countries, and many institutions have collaboration agreements with hospitals and universities worldwide for clinical training and research opportunities.",
      "Cultural Diversity: Kazakhstan’s diverse culture and heritage offer an enriching experience for international students, fostering cross-cultural understanding and exposure to different medical practices.",
      "Low Living Costs: The cost of living in Kazakhstan is relatively low, making it more accessible for international students. This includes affordable accommodation, food, and transportation.",
      "English-Medium Programs: Many medical universities in Kazakhstan offer MBBS programs in English, eliminating the need for students to learn a new language before starting their medical studies.",
      "Student-Friendly Environment: Kazakhstan is known for its welcoming and safe environment, making it a comfortable destination for international students.",
    ],
    steps: [
      "After completing the visa processing time, get a valid passport and fly for your dreams.",
      "Submission of educational certificates and other essential documents required for MBBS admission.",
      "Admission will be based on merit and performance during the interview.",
      "Candidates will get an offer letter from the university within a couple of days.",
      "Pay 1st-year tuition fee of the MBBS course.",
      "Apply for the visa procedure.",
      "After completing the visa processing time, get a valid passport and fly for your dreams.",
    ],
    requirements: [
      "Candidate must submit the application form.",
      "Candidates must have a NEET-UG examination scorecard along with the admit card.",
      "The academic mark sheet and passing certificate (original and copy).",
      "The candidate must carry a transfer certificate / leaving certificate from the previous institution.",
      "Foreign students must have a valid passport.",
      "Birth certificates must be submitted during admission required for proof of date of birth.",
      "Provisional allotment letter generated online.",
      "Candidates must submit caste certificate and validity certificate. (SC/ST/OBC category candidates)",
      "Submit your ID proof during admission time (Aadhaar card/ PAN card/ driving license/ passport).",
      "Conduct and character certificate.",
      "Candidates should submit the medical certificate.",
      "Carry passport size photographs required for MBBS admission.",
      "Proof of nationality of India / Passport/ domicile /nationality certificate.",
      "Passport size photographs.",
      "Demand draft.",
      "Gap certificate (Affidavit) (if applicable).",
      "Migration certificate (if applicable).",
    ],
  },
  // Add more countries as needed
};

export default countriesData;
